### ISSUE TITLE
Use updated wormhole-william

### ISSUE THREAD

**Issue by wuan** [LeastAuthority/dart_wormhole_william#42]
After the merge of the fix for Winden/Destiny interoperability issues  https://github.com/LeastAuthority/wormhole-william/pull/95 we should update our reference to https://github.com/LeastAuthority/wormhole-william.

**Comment by donpui** [comment]
I have updated wormhole-william with this commit: https://github.com/LeastAuthority/dart_wormhole_william/pull/40/commits/d50398d1717618f914f8f121c8947213e580b735 by merging ios_build changes to main branch.

**Comment by wuan** [comment]
An, haven't seen that. So we can close this.
